# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "Build IPA for appstore"
  lane :export_ipa do |options|
    VERSION_NAME = "1.0.1"
    VERSION_NUMBER = "3"
    SCHEME = "TravelGuide"
    APP_NAME = "TravelGuide"
    METHOD = "app-store"

    increment_version_number(
      version_number: VERSION_NAME # Set a specific version number
    )
    increment_build_number(
      build_number: VERSION_NUMBER, # set a specific number
      skip_info_plist: true
    )
    # xcode_select "/Applications/Xcode_13.1.app"
    build_app(
      configuration: "Release",
      scheme: SCHEME,
      export_method: METHOD,
      output_name: APP_NAME,
      clean: true
    )
  end

end
