# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Export .aab file for the Google Play"
  lane :export_aab do |options|
    VERSION_NAME = "1.0.1"
    VERSION_NUMBER = "3"
    gradle(
      task: 'clean',
    )
    gradle(
      task: 'bundle',
      build_type: 'release',
      properties: {
        "versionCode" => VERSION_NUMBER,
        "versionName" => VERSION_NAME,
      }
    )
  end
end
